import * as React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Vine from "@/components/Other/Vine";

const Poppins_init = Poppins({
  weight: "500",
  preload: false,
});

export const metadata: Metadata = {
  title: "Vhija",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="h-full"
    >
      <body
        className={cn(
          Poppins_init.className,
          "min-h-full w-full"
        )}
      >
        <div className="absolute w-full h-full overflow-hidden">
          <div className="2xl:scale-[.6] 2xl:-translate-y-[29rem] scale-[1.9] translate-y-52 sm:scale-[1.5] sm:translate-y-20 md:scale-[1.2] lg:scale-100 lg:-translate-y-10 xl:scale-75 xl:-translate-y-64">
            <Vine />
          </div>
        </div>

        <div className="w-full h-full">{children}</div>
      </body>
    </html>
  );
}
