import * as React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Vine from "@/components/Other/Vine";

const Poppins_init = Poppins({
  weight: "500",
  preload: false,
});

export const metadata: Metadata = {
  title: "Vhija",
  // description: "Generated by create next app",
  verification: {
    google: "iDULEhRSIYztsJjlaiCqd4dNu6mEz7lR_5JL0Ney2_4"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="h-full"
    >
      <body
        className={cn(
          Poppins_init.className,
          "h-full w-full"
        )}
      >
        <Vine />

        <div className="w-full h-full">{children}</div>
      </body>
    </html>
  );
}
